const keywordIcons: Array<[RegExp, string]> = [
  [/gym|workout|exercise|fitness|sport|run|swim|bike|cycling|squat|push-up|mobility|split|treadmill|sore muscle|injury|hike|garden|walk/, "fitness_center"],
  [/sleep|nap|bed|rest|tired|insomnia/, "bedtime"],
  [/read|book|article|writing|write|paper|draw|calligraphy|chinese|nom/, "menu_book"],
  [/music|song|ukulele|guitar|piano/, "music_note"],
  [/game|gaming|video game|football|watch(ed)? sport/, "sports_esports"],
  [/movie|film|tv|youtube|podcast|audiobook|cinema|netflix/, "movie"],
  [/cook|food|restaurant|cafe|chocolate|kefir|tea|coffee|sugar/, "restaurant"],
  [/clean|chore|wash|shower|bath|towel|house|home/, "cleaning_services"],
  [/family|wife|dad|friend|neighbou?r|people|convo|social|wedding|kids/, "groups"],
  [/work|job|coding|code|leetcode|meeting|call|freelance|todo|research|logseq/, "work"],
  [/anki|language|vietnamese|indonesian|class|learn|study|listening/, "school"],
  [/smok|vape|cigarette|alcohol|drink|substance|oil|micro|paracetamol|medicine|vit|supplement/, "medication"],
  [/meditat|mindful|nsdr|wimhoff|health podcast|fast|avoid|no /, "self_improvement"],
  [/travel|trip|plane|train|motorbike|van|beach|hotel|city|camp|picnic/, "travel_explore"],
  [/shop|shopping|money|trading|finance/, "shopping_bag"],
  [/panic|frustrat|bad|awful|sad|fun|achiev|think|emotion/, "psychology"],
];

export type ActivityIconCategory =
  | "Essentials"
  | "Health"
  | "Learning"
  | "Leisure"
  | "Food"
  | "People"
  | "Places"
  | "Work"
  | "Time"
  | "Objects";

/** A browsable, human-friendly catalog of Material Symbols Rounded glyphs. */
export const ACTIVITY_ICON_CHOICES: ReadonlyArray<{ name: string; category: ActivityIconCategory }> = [
  { name: "category", category: "Essentials" },
  { name: "favorite", category: "Essentials" },
  { name: "star", category: "Essentials" },
  { name: "bookmark", category: "Essentials" },
  { name: "flag", category: "Essentials" },
  { name: "label", category: "Essentials" },
  { name: "check_circle", category: "Essentials" },
  { name: "task_alt", category: "Essentials" },
  { name: "done", category: "Essentials" },
  { name: "add_task", category: "Essentials" },
  { name: "home", category: "Essentials" },
  { name: "settings", category: "Essentials" },
  { name: "search", category: "Essentials" },
  { name: "link", category: "Essentials" },
  { name: "attach_file", category: "Essentials" },
  { name: "fitness_center", category: "Health" },
  { name: "directions_walk", category: "Health" },
  { name: "directions_run", category: "Health" },
  { name: "directions_bike", category: "Health" },
  { name: "pool", category: "Health" },
  { name: "sports_soccer", category: "Health" },
  { name: "sports_basketball", category: "Health" },
  { name: "sports_tennis", category: "Health" },
  { name: "sports_golf", category: "Health" },
  { name: "sports_martial_arts", category: "Health" },
  { name: "self_improvement", category: "Health" },
  { name: "spa", category: "Health" },
  { name: "psychology", category: "Health" },
  { name: "mood", category: "Health" },
  { name: "sentiment_satisfied", category: "Health" },
  { name: "sentiment_dissatisfied", category: "Health" },
  { name: "bedtime", category: "Health" },
  { name: "local_hospital", category: "Health" },
  { name: "medication", category: "Health" },
  { name: "vaccines", category: "Health" },
  { name: "healing", category: "Health" },
  { name: "no_smoking", category: "Health" },
  { name: "menu_book", category: "Learning" },
  { name: "edit_note", category: "Learning" },
  { name: "article", category: "Learning" },
  { name: "draw", category: "Learning" },
  { name: "brush", category: "Learning" },
  { name: "translate", category: "Learning" },
  { name: "language", category: "Learning" },
  { name: "school", category: "Learning" },
  { name: "science", category: "Learning" },
  { name: "calculate", category: "Learning" },
  { name: "music_note", category: "Leisure" },
  { name: "headphones", category: "Leisure" },
  { name: "mic", category: "Leisure" },
  { name: "movie", category: "Leisure" },
  { name: "tv", category: "Leisure" },
  { name: "podcasts", category: "Leisure" },
  { name: "sports_esports", category: "Leisure" },
  { name: "casino", category: "Leisure" },
  { name: "theater_comedy", category: "Leisure" },
  { name: "celebration", category: "Leisure" },
  { name: "restaurant", category: "Food" },
  { name: "local_cafe", category: "Food" },
  { name: "local_bar", category: "Food" },
  { name: "cake", category: "Food" },
  { name: "lunch_dining", category: "Food" },
  { name: "fastfood", category: "Food" },
  { name: "local_grocery_store", category: "Food" },
  { name: "bakery_dining", category: "Food" },
  { name: "coffee", category: "Food" },
  { name: "water_drop", category: "Food" },
  { name: "groups", category: "People" },
  { name: "person", category: "People" },
  { name: "family_restroom", category: "People" },
  { name: "handshake", category: "People" },
  { name: "volunteer_activism", category: "People" },
  { name: "pets", category: "People" },
  { name: "child_care", category: "People" },
  { name: "support_agent", category: "People" },
  { name: "travel_explore", category: "Places" },
  { name: "flight", category: "Places" },
  { name: "train", category: "Places" },
  { name: "directions_car", category: "Places" },
  { name: "two_wheeler", category: "Places" },
  { name: "beach_access", category: "Places" },
  { name: "camping", category: "Places" },
  { name: "hotel", category: "Places" },
  { name: "map", category: "Places" },
  { name: "park", category: "Places" },
  { name: "forest", category: "Places" },
  { name: "sunny", category: "Places" },
  { name: "cloud", category: "Places" },
  { name: "work", category: "Work" },
  { name: "business_center", category: "Work" },
  { name: "laptop_mac", category: "Work" },
  { name: "code", category: "Work" },
  { name: "terminal", category: "Work" },
  { name: "meeting_room", category: "Work" },
  { name: "call", category: "Work" },
  { name: "email", category: "Work" },
  { name: "design_services", category: "Work" },
  { name: "construction", category: "Work" },
  { name: "shopping_bag", category: "Objects" },
  { name: "shopping_cart", category: "Objects" },
  { name: "payments", category: "Objects" },
  { name: "account_balance_wallet", category: "Objects" },
  { name: "cleaning_services", category: "Objects" },
  { name: "wash", category: "Objects" },
  { name: "shower", category: "Objects" },
  { name: "bathtub", category: "Objects" },
  { name: "laundry", category: "Objects" },
  { name: "palette", category: "Objects" },
  { name: "camera_alt", category: "Objects" },
  { name: "photo_camera", category: "Objects" },
  { name: "lightbulb", category: "Objects" },
  { name: "rocket_launch", category: "Objects" },
  { name: "build", category: "Objects" },
  { name: "lock", category: "Objects" },
  { name: "key", category: "Objects" },
  { name: "notifications", category: "Objects" },
  { name: "cloud_done", category: "Objects" },
  { name: "public", category: "Objects" },
  { name: "location_on", category: "Objects" },
  { name: "dark_mode", category: "Objects" },
  { name: "light_mode", category: "Objects" },
  { name: "calendar_month", category: "Time" },
  { name: "event", category: "Time" },
  { name: "alarm", category: "Time" },
  { name: "schedule", category: "Time" },
  { name: "timer", category: "Time" },
  { name: "hourglass_top", category: "Time" },
  { name: "history", category: "Time" },
  { name: "update", category: "Time" },
  { name: "trending_up", category: "Time" },
  { name: "trending_down", category: "Time" },
];

/** Resolve a Daylio activity to a stable Material Symbols Rounded name. */
export function iconForActivity(name: string, sourceIconId?: string) {
  // Seed data already uses Material Symbols names. Daylio's numeric IDs are
  // retained as provenance but are not a portable public icon catalog.
  if (sourceIconId && sourceIconId !== "category" && /[a-z_]/i.test(sourceIconId) && !/^\d+$/.test(sourceIconId)) return sourceIconId;
  const normalized = name.trim().toLowerCase();
  return keywordIcons.find(([pattern]) => pattern.test(normalized))?.[1] ?? "category";
}

export const UI_ICONS = {
  add: "add",
  calendar: "calendar_month",
  check: "check",
  close: "close",
  delete: "delete",
  edit: "edit",
  entries: "format_list_bulleted",
  expand: "expand_more",
  export: "download",
  log: "add_circle",
  moveDown: "keyboard_arrow_down",
  moveUp: "keyboard_arrow_up",
  restore: "unarchive",
  search: "search",
  settings: "tune",
  archive: "archive",
  sync: "cloud_done",
} as const;
